// ItemCatalog.swift — Master catalog of every addressable item (Part 1: Always + Government + Transport + Housing)
import Foundation

enum ItemCatalog {

    // MARK: - All items merged
    static var all: [CatalogItem] { government + transport + housing + financial + allLifestyle }

    // MARK: - 🏛️ GOVERNMENT (always shown)
    static let government: [CatalogItem] = [
        CatalogItem(id: "usps", title: "USPS Mail Forwarding", emoji: "📬",
                    category: .postal, priority: .critical, tMinusDays: -30,
                    deepLinkURL: URL(string: "https://moversguide.usps.com"),
                    brandColorHex: "#004B87", isHeroItem: true, alwaysInclude: true),
        CatalogItem(id: "dmv_license", title: "Driver's License / State ID", emoji: "🪪",
                    category: .government, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://dmv.org"),
                    brandColorHex: "#7D3C98", alwaysInclude: true),
        CatalogItem(id: "voter", title: "Voter Registration", emoji: "🗳️",
                    category: .government, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://vote.gov"),
                    brandColorHex: "#1A5276", alwaysInclude: true),
        CatalogItem(id: "irs", title: "IRS Address (Form 8822)", emoji: "🏛️",
                    category: .government, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.irs.gov/forms-pubs/about-form-8822"),
                    brandColorHex: "#1B4F72", alwaysInclude: true),
        CatalogItem(id: "ssa", title: "Social Security Administration", emoji: "🛡️",
                    category: .government, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.ssa.gov"),
                    brandColorHex: "#154360", alwaysInclude: true),
        CatalogItem(id: "dmv_vehicle", title: "Vehicle Registration (DMV)", emoji: "🚗",
                    category: .government, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://dmv.org"),
                    brandColorHex: "#7D3C98", requiresAny: [.hasCar, .hasMotorcycle, .hasMultipleCars]),
        CatalogItem(id: "passport", title: "US Passport (address on file)", emoji: "🛂",
                    category: .government, priority: .low, tMinusDays: 30,
                    deepLinkURL: URL(string: "https://travel.state.gov"),
                    brandColorHex: "#1A5276", alwaysInclude: true),
        CatalogItem(id: "medicare", title: "Medicare / Medicaid", emoji: "⚕️",
                    category: .government, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.medicare.gov"),
                    brandColorHex: "#1A237E", requiresAny: [.hasMedicare, .isRetired]),
        CatalogItem(id: "va", title: "VA Benefits", emoji: "🎖️",
                    category: .government, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.va.gov"),
                    brandColorHex: "#003087", requires: [.isVeteran]),
        CatalogItem(id: "prof_license", title: "Professional License (state board)", emoji: "📋",
                    category: .legal, priority: .high, tMinusDays: -14,
                    brandColorHex: "#8E44AD", requires: [.hasProfessionalLicenses]),
        CatalogItem(id: "tsa_precheck", title: "TSA PreCheck / Global Entry / CLEAR", emoji: "✈️",
                    category: .government, priority: .high, tMinusDays: -7,
                    brandColorHex: "#004B87", requires: [.hasTSAPreCheck]),
    ]

    // MARK: - 🚗 TRANSPORT
    static let transport: [CatalogItem] = [
        CatalogItem(id: "uber_address", title: "Update Uber Home Address", emoji: "🚕",
                    category: .other, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.uber.com"),
                    brandColorHex: "#141414", requiresAny: [.usesRideShare]),
        CatalogItem(id: "lyft_address", title: "Update Lyft Home Address", emoji: "🚕",
                    category: .other, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.lyft.com"),
                    brandColorHex: "#FF00BF", requiresAny: [.usesRideShare]),
        CatalogItem(id: "toll_ezpass", title: "Toll Transponder (E-ZPass / SunPass / FasTrak)", emoji: "🛣️",
                    category: .other, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.e-zpassiag.com"),
                    brandColorHex: "#1B4F72", requires: [.hasTollRoads]),
        CatalogItem(id: "aaa", title: "AAA Membership Address", emoji: "🔧",
                    category: .other, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.aaa.com"),
                    brandColorHex: "#003087", requiresAny: [.hasCar, .hasMotorcycle]),
        CatalogItem(id: "tesla", title: "Tesla Account / MyEV Address", emoji: "⚡",
                    category: .other, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.tesla.com"),
                    brandColorHex: "#CC0000", requires: [.hasElectricVehicle]),
        CatalogItem(id: "google_maps", title: "Google Maps Home Address", emoji: "🗺️",
                    category: .other, priority: .low, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://maps.google.com"),
                    brandColorHex: "#4285F4", alwaysInclude: true),
        CatalogItem(id: "apple_maps", title: "Apple Maps Home Address", emoji: "🍎",
                    category: .other, priority: .low, tMinusDays: 1,
                    brandColorHex: "#555555", alwaysInclude: true),
        CatalogItem(id: "airline_loyalty", title: "Airline Loyalty (Delta, United, etc.)", emoji: "✈️",
                    category: .subscriptions, priority: .low, tMinusDays: 14,
                    brandColorHex: "#003087", requires: [.hasAirlineLoyalty]),
    ]

    // MARK: - 🏠 HOUSING / UTILITIES
    static let housing: [CatalogItem] = [
        CatalogItem(id: "electric", title: "Electric / Power Company", emoji: "💡",
                    category: .utilities, priority: .critical, tMinusDays: -21,
                    brandColorHex: "#F5A623", alwaysInclude: true),
        CatalogItem(id: "gas", title: "Natural Gas Provider", emoji: "🔥",
                    category: .utilities, priority: .critical, tMinusDays: -21,
                    brandColorHex: "#E67E22", alwaysInclude: true),
        CatalogItem(id: "water", title: "Water / Sewer Service", emoji: "💧",
                    category: .utilities, priority: .high, tMinusDays: -14,
                    brandColorHex: "#1ABC9C", alwaysInclude: true),
        CatalogItem(id: "trash", title: "Trash & Recycling", emoji: "♻️",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#27AE60", alwaysInclude: true),
        CatalogItem(id: "internet", title: "Internet Provider", emoji: "📶",
                    category: .utilities, priority: .critical, tMinusDays: -21,
                    brandColorHex: "#2E86C1", alwaysInclude: true),
        CatalogItem(id: "home_security", title: "Home Security System", emoji: "🔒",
                    category: .utilities, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.ring.com"),
                    brandColorHex: "#1C2833", requires: [.hasHomeSecurity]),
        CatalogItem(id: "hoa", title: "HOA Account & Address", emoji: "🏘️",
                    category: .other, priority: .high, tMinusDays: -14,
                    brandColorHex: "#626567", requires: [.hasHOA]),
        CatalogItem(id: "solar", title: "Solar Panel Provider", emoji: "☀️",
                    category: .utilities, priority: .high, tMinusDays: -14,
                    brandColorHex: "#F39C12", requires: [.hasSolar]),
        CatalogItem(id: "parking_permit", title: "Parking Authorities & Residential Permits", emoji: "🅿️",
                    category: .other, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#C0392B", requires: [.needsParkingPermit]),
    ]

    // MARK: - 💳 FINANCIAL (always shown — institution-specific tasks added separately)
    static let financial: [CatalogItem] = [
        CatalogItem(id: "paypal", title: "PayPal Address", emoji: "💸",
                    category: .financial, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.paypal.com"),
                    brandColorHex: "#003087", alwaysInclude: true),
        CatalogItem(id: "venmo", title: "Venmo Address", emoji: "💸",
                    category: .financial, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.venmo.com"),
                    brandColorHex: "#3D95CE", alwaysInclude: true),
        CatalogItem(id: "cashapp", title: "Cash App Address", emoji: "💵",
                    category: .financial, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://cash.app"),
                    brandColorHex: "#00D632", alwaysInclude: true),
        CatalogItem(id: "student_loans", title: "Student Loan Servicer", emoji: "🎓",
                    category: .education, priority: .critical, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://studentaid.gov"),
                    brandColorHex: "#1A5276", requires: [.hasStudentLoans]),
        CatalogItem(id: "mortgage", title: "Mortgage Servicer", emoji: "🏡",
                    category: .financial, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#C0392B", requires: [.hasMortgage]),
        CatalogItem(id: "financial_advisor", title: "Financial Advisor / CPA", emoji: "📊",
                    category: .financial, priority: .medium, tMinusDays: 7,
                    brandColorHex: "#27AE60", requires: [.hasFinancialAdvisor]),
        CatalogItem(id: "crypto_exchange", title: "Hardware Wallets & Crypto Exchanges (Coinbase, etc.)", emoji: "🪙",
                    category: .financial, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#F39C12", requires: [.holdsCrypto]),
        CatalogItem(id: "pension", title: "Pension Administrators & 401k/IRA", emoji: "🏦",
                    category: .financial, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#1F618D", requires: [.hasPension]),
    ]
}
