// ItemCatalog+Digital.swift — App Stores, Subscription Boxes, News/Magazines, Smart Home, Estate & Digital Identity
import Foundation

extension ItemCatalog {

    static var allDigital: [CatalogItem] {
        appStores + subscriptionBoxes + newsMagazines + smartHome + homeServices + estatePlanning + digitalIdentity + communityFaith
    }

    // MARK: - 📱 App Stores & Digital Ecosystems

    static let appStores: [CatalogItem] = [
        CatalogItem(id: "apple_id_billing", title: "Apple ID / App Store Billing Address", emoji: "🍎",
                    category: .digital, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://appleid.apple.com/"),
                    brandColorHex: "#555555",
                    requiresAny: [.usesAppleAppStore, .usesApplePay, .usesAppleTVPlus, .usesAppleMusic], reviewFamily: .shopping),
        CatalogItem(id: "google_account_billing", title: "Google Account / Play Store Billing", emoji: "🤖",
                    category: .digital, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://myaccount.google.com/payments-and-subscriptions"),
                    brandColorHex: "#4285F4",
                    requiresAny: [.usesGooglePlay, .usesGooglePay], reviewFamily: .shopping),
        CatalogItem(id: "microsoft_account", title: "Microsoft Account / Xbox Billing Address", emoji: "🪟",
                    category: .digital, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://account.microsoft.com/billing/"),
                    brandColorHex: "#00A4EF",
                    requires: [.usesGamingSubs], reviewFamily: .shopping),
        CatalogItem(id: "playstation_account", title: "PlayStation Network Billing Address", emoji: "🎮",
                    category: .digital, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.playstation.com/en-us/playstation-network/"),
                    brandColorHex: "#003087",
                    requires: [.usesGamingSubs], reviewFamily: .shopping),
        CatalogItem(id: "nintendo_account", title: "Nintendo Account Billing Address", emoji: "🎮",
                    category: .digital, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://accounts.nintendo.com/"),
                    brandColorHex: "#E4000F",
                    requires: [.usesGamingSubs], reviewFamily: .shopping),
    ]

    // MARK: - 📦 Subscription Boxes & Physical Clubs

    static let subscriptionBoxes: [CatalogItem] = [
        CatalogItem(id: "beauty_box", title: "Beauty box subscriptions", emoji: "💄",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    brandColorHex: "#E91E8C",
                    requires: [.usesBeautyBox], reviewFamily: .shopping,
                    searchTerms: ["IPSY", "Allure"],
                    legacyTitles: ["Beauty Box Subscription (Birchbox / IPSY / Allure)"],
                    obsoleteDeepLinks: ["https://www.ipsy.com/profile"]),
        CatalogItem(id: "fabfitfun", title: "FabFitFun Shipping Address", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    deepLinkURL: URL(string: "https://fabfitfun.com/account/"),
                    brandColorHex: "#FF6B6B",
                    requires: [.usesFabFitFun], reviewFamily: .shopping),
        CatalogItem(id: "bespoke_post", title: "Bespoke Post Shipping Address", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    deepLinkURL: URL(string: "https://bespokepost.com/account"),
                    brandColorHex: "#2C3E50",
                    requires: [.usesBespokePost], reviewFamily: .shopping),
        CatalogItem(id: "wine_club", title: "Winery & other wine-club memberships", emoji: "🍷",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    brandColorHex: "#722F37",
                    requires: [.usesWineClub], reviewFamily: .shopping,
                    searchTerms: ["wine subscription", "vineyard", "tasting room"],
                    legacyTitles: ["Wine Club Delivery Address (Winc / Firstleaf)"],
                    obsoleteDeepLinks: ["https://www.winc.com/account"]),
        CatalogItem(id: "coffee_subscription", title: "Coffee subscriptions & local roaster deliveries", emoji: "☕",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    brandColorHex: "#4A2C2A",
                    requires: [.usesCoffeeSubscription], reviewFamily: .shopping,
                    searchTerms: ["coffee beans", "roaster"],
                    legacyTitles: ["Coffee Subscription Address (Trade / Peet's)"],
                    obsoleteDeepLinks: ["https://www.drinktrade.com/account"]),
        CatalogItem(id: "kids_activity_box", title: "Children's activity & learning boxes", emoji: "🧸",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    brandColorHex: "#FF6B35",
                    requires: [.usesKidsCrateBox], reviewFamily: .family,
                    legacyTitles: ["Kids Activity Box (KiwiCo / Little Passports)", "KiwiCo / Little Passports Delivery"],
                    obsoleteDeepLinks: ["https://www.kiwico.com/account"]),
        CatalogItem(id: "book_of_the_month", title: "Book of the Month Shipping Address", emoji: "📚",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    deepLinkURL: URL(string: "https://www.bookofthemonth.com/account"),
                    brandColorHex: "#E74C3C",
                    requires: [.usesBookOfTheMonth], reviewFamily: .shopping),
        CatalogItem(id: "snack_box", title: "Snack & specialty treat boxes", emoji: "🍿",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    brandColorHex: "#27AE60",
                    requires: [.usesSnackBox], reviewFamily: .shopping,
                    legacyTitles: ["Snack Box Subscription (Graze / Snack Crate)"],
                    obsoleteDeepLinks: ["https://www.graze.com/us/account"]),
        CatalogItem(id: "clothing_box", title: "Other clothing & styling boxes", emoji: "👗",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    brandColorHex: "#4ECDC4",
                    requires: [.usesClothingBox], reviewFamily: .shopping,
                    legacyTitles: ["Clothing Subscription (Stitch Fix / Trunk Club)"],
                    obsoleteDeepLinks: ["https://www.stitchfix.com/account"]),
    ]

    // MARK: - 📰 News & Magazines

    static let newsMagazines: [CatalogItem] = [
        CatalogItem(id: "nyt_subscription", title: "New York Times Subscription Address", emoji: "📰",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://myaccount.nytimes.com/"),
                    brandColorHex: "#000000",
                    requires: [.usesNewYorkTimes], reviewFamily: .shopping),
        CatalogItem(id: "wapo_subscription", title: "Washington Post Subscription Address", emoji: "📰",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://account.washingtonpost.com/"),
                    brandColorHex: "#1A1A1A",
                    requires: [.usesWashingtonPost], reviewFamily: .shopping),
        CatalogItem(id: "wsj_subscription", title: "Wall Street Journal Subscription Address", emoji: "📰",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://customercenter.wsj.com/"),
                    brandColorHex: "#003DA5",
                    requires: [.usesWallStreetJournal], reviewFamily: .shopping),
        CatalogItem(id: "local_newspaper", title: "Local Newspaper Subscription Address", emoji: "📰",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    brandColorHex: "#626567",
                    requires: [.usesLocalNewspaper], reviewFamily: .shopping),
        CatalogItem(id: "magazine_subscription", title: "Magazine Subscriptions (Vogue / Wired / GQ)", emoji: "📖",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    brandColorHex: "#8E44AD",
                    requires: [.usesMagazineSubscription], reviewFamily: .shopping),
    ]

    // MARK: - 🏠 Smart Home & Security

    static let smartHome: [CatalogItem] = [
        CatalogItem(id: "nest_ecobee", title: "Smart Thermostat App Address (Nest / Ecobee)", emoji: "🌡️",
                    category: .utilities, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://home.nest.com/"),
                    brandColorHex: "#00A59B",
                    requires: [.hasSmartThermostat], reviewFamily: .home, discoveryContext: .housing),
        CatalogItem(id: "smart_locks", title: "Smart Lock System — Update Account Address", emoji: "🔐",
                    category: .utilities, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.august.com/"),
                    brandColorHex: "#2C3E50",
                    requires: [.hasSmartLocks], reviewFamily: .home, discoveryContext: .housing),
        CatalogItem(id: "video_doorbell", title: "Video Doorbell Account (Ring / Arlo)", emoji: "🔔",
                    category: .utilities, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://account.ring.com/"),
                    brandColorHex: "#1C2833",
                    requires: [.hasVideoDoorbells], reviewFamily: .home, discoveryContext: .housing),
        CatalogItem(id: "pool_spa_service", title: "Pool / Spa Maintenance Service", emoji: "🏊",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#1ABC9C",
                    requires: [.hasPoolSpa], reviewFamily: .home, discoveryContext: .housing),
    ]

    // MARK: - 🛺 Home Services (Physical Recurring)

    static let homeServices: [CatalogItem] = [
        CatalogItem(id: "lawn_care_service", title: "Lawn Care / Landscaping Service", emoji: "🌿",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#27AE60",
                    requires: [.hasLawnCareService], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
        CatalogItem(id: "snow_removal_service", title: "Snow Removal Service", emoji: "❄️",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#AED6F1",
                    requires: [.hasSnowRemovalService], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
        CatalogItem(id: "pest_control", title: "Pest Control Service", emoji: "🐜",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#E67E22",
                    requires: [.hasPestControlService], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
        CatalogItem(id: "cleaning_service", title: "House Cleaning Service", emoji: "🧹",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#5D6D7E",
                    requires: [.hasCleaningService], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
        CatalogItem(id: "window_washing", title: "Window Washing Service", emoji: "🪟",
                    category: .utilities, priority: .low, tMinusDays: 7,
                    brandColorHex: "#85C1E9",
                    requires: [.hasWindowWashingService], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
        CatalogItem(id: "septic_service", title: "Septic Tank / Well Service Provider", emoji: "💧",
                    category: .utilities, priority: .high, tMinusDays: -14,
                    brandColorHex: "#1B4F72",
                    requiresAny: [.hasSepticTank, .hasWell], reviewFamily: .home, discoveryContext: .housing, moveAction: .reviewTransfer),
    ]

    // MARK: - 📜 Estate & Legal Planning

    static let estatePlanning: [CatalogItem] = [
        CatalogItem(id: "will_update", title: "Will & Testament — Review for New State Laws", emoji: "📜",
                    category: .estate, priority: .high, tMinusDays: 14,
                    brandColorHex: "#2C3E50",
                    requires: [.hasWill], reviewFamily: .work),
        CatalogItem(id: "living_trust", title: "Living Trust — Retitle Property into Trust", emoji: "📜",
                    category: .estate, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#1B4F72",
                    requires: [.hasTrust], reviewFamily: .work),
        CatalogItem(id: "power_of_attorney", title: "Power of Attorney — Update Address on Record", emoji: "✍️",
                    category: .estate, priority: .high, tMinusDays: 14,
                    brandColorHex: "#7D3C98",
                    requires: [.hasPowerOfAttorney], reviewFamily: .work),
        CatalogItem(id: "healthcare_directive", title: "Healthcare Directive / Living Will", emoji: "🏥",
                    category: .estate, priority: .high, tMinusDays: 14,
                    brandColorHex: "#C0392B",
                    requires: [.hasHealthcareDirective], reviewFamily: .work),
        CatalogItem(id: "beneficiary_review", title: "Beneficiary Designations — Life Insurance & Retirement", emoji: "🎯",
                    category: .estate, priority: .critical, tMinusDays: -7,
                    brandColorHex: "#E74C3C",
                    requiresAny: [.hasLifeInsurance, .hasInvestmentAccounts, .hasPension], reviewFamily: .work),
        CatalogItem(id: "safe_deposit_box", title: "Safe Deposit Box — Update Bank Branch Address", emoji: "🗄️",
                    category: .estate, priority: .medium, tMinusDays: 7,
                    brandColorHex: "#212F3D",
                    requires: [.hasSafeDepositBox], poiCategory: .bank, reviewFamily: .work),
    ]

    // MARK: - 🌐 Digital Identity

    static let digitalIdentity: [CatalogItem] = [
        CatalogItem(id: "google_maps_home", title: "Google Maps — Update Home & Work Address", emoji: "🗺️",
                    category: .digital, priority: .low, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://maps.google.com"),
                    brandColorHex: "#4285F4", alwaysInclude: true, reviewFamily: .work, requiresConfirmation: true, canonicalID: "google_maps"),
        CatalogItem(id: "linkedin_location", title: "LinkedIn — Update Profile Location", emoji: "🔗",
                    category: .digital, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.linkedin.com/in/"),
                    brandColorHex: "#0077B5", alwaysInclude: true, reviewFamily: .work, requiresConfirmation: true, canonicalID: "linkedin"),
        CatalogItem(id: "google_business_profile", title: "Google Business Profile — Update Address", emoji: "🏢",
                    category: .digital, priority: .critical, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://business.google.com/"),
                    brandColorHex: "#4285F4",
                    requires: [.hasGoogleBusinessProfile], reviewFamily: .work),
        CatalogItem(id: "personal_website", title: "Personal / Business Website — Update Address", emoji: "🌐",
                    category: .digital, priority: .medium, tMinusDays: 0,
                    brandColorHex: "#2E86C1",
                    requires: [.hasPersonalWebsite], reviewFamily: .work),
        CatalogItem(id: "domain_registrar", title: "Domain Registrar WHOIS Address (GoDaddy / Namecheap)", emoji: "🖥️",
                    category: .digital, priority: .medium, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://account.godaddy.com/"),
                    brandColorHex: "#1BBB77",
                    requires: [.usesDomainRegistrar], reviewFamily: .work),
        CatalogItem(id: "password_manager", title: "Password Manager — Update Saved Address (1Password / LastPass)", emoji: "🔑",
                    category: .digital, priority: .low, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://1password.com/"),
                    brandColorHex: "#1A6FD8",
                    requires: [.usesPasswordManager], reviewFamily: .work),
    ]

    // MARK: - 🌿 Community, Faith & Philanthropy

    static let communityFaith: [CatalogItem] = [
        CatalogItem(id: "religious_institution", title: "Religious Institution / Church — Update Directory", emoji: "⛪",
                    category: .other, priority: .low, tMinusDays: 14,
                    brandColorHex: "#6C5CE7",
                    requires: [.attendsReligiousInstitution], reviewFamily: .memberships),
        CatalogItem(id: "social_club", title: "Social / Country Club — Update Member Address", emoji: "🎭",
                    category: .other, priority: .low, tMinusDays: 14,
                    brandColorHex: "#2C3E50",
                    requires: [.belongsToSocialClub], reviewFamily: .memberships),
        CatalogItem(id: "charitable_donations", title: "Charitable Donations — Update Donor Address for Tax Receipts", emoji: "💝",
                    category: .other, priority: .medium, tMinusDays: 7,
                    brandColorHex: "#E74C3C",
                    requires: [.donatesCharitably], reviewFamily: .memberships),
        CatalogItem(id: "political_contributions", title: "Political Contribution Records — Update Address", emoji: "🗳️",
                    category: .government, priority: .medium, tMinusDays: 7,
                    brandColorHex: "#1A5276",
                    requires: [.hasPoliticalContributions], reviewFamily: .memberships),
    ]
}
