// ItemCatalog+Lifestyle.swift — Part 2: Shopping, Streaming, Fitness, Pets, Healthcare, Employer, Education, Legal
import Foundation

extension ItemCatalog {

    static var allLifestyle: [CatalogItem] {
        shopping + foodDelivery + streaming + fitness + memberships + pets + healthcare + employer + education + legal
    }

    // MARK: - 🛍️ SHOPPING
    static let shopping: [CatalogItem] = [
        CatalogItem(id: "amazon", title: "Amazon — Billing & Shipping Address", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: -3,
                    deepLinkURL: URL(string: "https://www.amazon.com/a/addresses"),
                    brandColorHex: "#FF9900", requires: [.usesAmazon]),
        CatalogItem(id: "amazon_prime", title: "Amazon Prime Membership", emoji: "⭐",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.amazon.com/prime"),
                    brandColorHex: "#00A8E0", requires: [.usesAmazon]),
        CatalogItem(id: "costco", title: "Costco Membership Address", emoji: "🏬",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.costco.com/account-settings"),
                    brandColorHex: "#005DAA", requires: [.usesCostco]),
        CatalogItem(id: "samsclub", title: "Sam's Club Membership Address", emoji: "🏬",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.samsclub.com"),
                    brandColorHex: "#004C97", requires: [.usesSamsClub]),
        CatalogItem(id: "bjs", title: "BJ's Wholesale Membership", emoji: "🏬",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.bjs.com"),
                    brandColorHex: "#E31837", requires: [.usesBJs]),
        CatalogItem(id: "target", title: "Target Circle & RedCard Address", emoji: "🎯",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.target.com/account"),
                    brandColorHex: "#CC0000", requires: [.usesTarget]),
        CatalogItem(id: "walmart", title: "Walmart / Walmart+ Address", emoji: "🟡",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.walmart.com/account"),
                    brandColorHex: "#0071CE", requires: [.usesWalmart]),
        CatalogItem(id: "rei", title: "REI Co-op Membership Address", emoji: "🏕️",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.rei.com/account"),
                    brandColorHex: "#3A5F0B", requires: [.usesREI]),
        CatalogItem(id: "bestbuy", title: "Best Buy / Geek Squad Address", emoji: "💙",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.bestbuy.com/profile/ss/myaccount"),
                    brandColorHex: "#003B64", requires: [.usesBestBuy]),
        CatalogItem(id: "ikea", title: "IKEA Family Membership Address", emoji: "🪑",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.ikea.com"),
                    brandColorHex: "#0058A3", requires: [.usesIKEA]),
        CatalogItem(id: "wayfair", title: "Wayfair Shipping Address", emoji: "🪴",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.wayfair.com/account/addresses"),
                    brandColorHex: "#7B2D8B", requires: [.usesWayfair]),
        CatalogItem(id: "publix", title: "Publix Account", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#43B02A", requires: [.usesPublix]),
        CatalogItem(id: "heb", title: "H-E-B Account", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#E21836", requires: [.usesHEB]),
        CatalogItem(id: "meijer", title: "mPerks / Meijer Account", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#003A70", requires: [.usesMeijer]),
        CatalogItem(id: "wegmans", title: "Wegmans Shoppers Club", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#702F44", requires: [.usesWegmans]),
        CatalogItem(id: "kroger", title: "Kroger / King Soopers / Ralphs", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#0054A4", requires: [.usesKroger]),
        CatalogItem(id: "safeway", title: "Safeway / Vons / Pavilions", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#E21836", requires: [.usesSafeway]),
        CatalogItem(id: "albertsons", title: "Albertsons for U", emoji: "🛒",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#003A70", requires: [.usesAlbertsons]),
    ]

    // MARK: - 🍕 FOOD DELIVERY
    static let foodDelivery: [CatalogItem] = [
        CatalogItem(id: "doordash", title: "DoorDash Default Address", emoji: "🍕",
                    category: .subscriptions, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.doordash.com"),
                    brandColorHex: "#FF3008", requires: [.usesDoorDash]),
        CatalogItem(id: "ubereats", title: "Uber Eats Default Address", emoji: "🍔",
                    category: .subscriptions, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.ubereats.com"),
                    brandColorHex: "#06C167", requires: [.usesUberEats]),
        CatalogItem(id: "grubhub", title: "Grubhub Default Address", emoji: "🌮",
                    category: .subscriptions, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.grubhub.com"),
                    brandColorHex: "#F63440", requires: [.usesGrubhub]),
        CatalogItem(id: "instacart", title: "Instacart Delivery Address", emoji: "🛒",
                    category: .subscriptions, priority: .high, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.instacart.com"),
                    brandColorHex: "#43B02A", requires: [.usesInstacart]),
        CatalogItem(id: "amazon_fresh", title: "Amazon Fresh Delivery Address", emoji: "🥦",
                    category: .subscriptions, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.amazon.com/fmc/storefront"),
                    brandColorHex: "#00A8E0", requires: [.usesAmazonFresh]),
        CatalogItem(id: "hellofresh", title: "HelloFresh Delivery Address", emoji: "🥗",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.hellofresh.com/account"),
                    brandColorHex: "#6CC04A", requires: [.usesHelloFresh]),
        CatalogItem(id: "blueapron", title: "Blue Apron Delivery Address", emoji: "🍳",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.blueapron.com/account"),
                    brandColorHex: "#39B3E6", requires: [.usesBlueApron]),
        CatalogItem(id: "mealkit_other", title: "Meal Kit Service Address", emoji: "🧑‍🍳",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    brandColorHex: "#E67E22", requires: [.usesOtherMealKit]),
    ]

    // MARK: - 📺 STREAMING
    static let streaming: [CatalogItem] = [
        CatalogItem(id: "netflix", title: "Netflix Billing Address", emoji: "🎬",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.netflix.com/account"),
                    brandColorHex: "#E50914", requires: [.usesNetflix]),
        CatalogItem(id: "hulu", title: "Hulu Billing Address", emoji: "📺",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://auth.hulu.com/user/login"),
                    brandColorHex: "#1CE783", requires: [.usesHulu]),
        CatalogItem(id: "disneyplus", title: "Disney+ Billing Address", emoji: "✨",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.disneyplus.com/account"),
                    brandColorHex: "#113CCF", requires: [.usesDisneyPlus]),
        CatalogItem(id: "hbomax", title: "Max (HBO) Billing Address", emoji: "🎭",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.max.com/account"),
                    brandColorHex: "#5822B4", requires: [.usesHBOMax]),
        CatalogItem(id: "appletv", title: "Apple TV+ / iTunes Billing Address", emoji: "🍎",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://appleid.apple.com"),
                    brandColorHex: "#555555", requires: [.usesAppleTVPlus]),
        CatalogItem(id: "paramount", title: "Paramount+ Billing Address", emoji: "⭐",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.paramountplus.com/account"),
                    brandColorHex: "#0064FF", requires: [.usesParamountPlus]),
        CatalogItem(id: "peacock", title: "Peacock Billing Address", emoji: "🦚",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.peacocktv.com/account"),
                    brandColorHex: "#F5A623", requires: [.usesPeacock]),
        CatalogItem(id: "spotify", title: "Spotify Billing Address", emoji: "🎵",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.spotify.com/account"),
                    brandColorHex: "#1DB954", requires: [.usesSpotify]),
        CatalogItem(id: "applemusic", title: "Apple Music / Apple ID Address", emoji: "🎶",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://appleid.apple.com"),
                    brandColorHex: "#FC3C44", requires: [.usesAppleMusic]),
        CatalogItem(id: "siriusxm", title: "SiriusXM Billing Address", emoji: "📻",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.siriusxm.com/account"),
                    brandColorHex: "#0000EB", requires: [.usesSiriusXM]),
        CatalogItem(id: "youtube_premium", title: "YouTube Premium Billing", emoji: "▶️",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.youtube.com/account_billing"),
                    brandColorHex: "#FF0000", requires: [.usesYouTubePremium]),
        CatalogItem(id: "gaming_subs", title: "Gaming Subscriptions (Xbox/PS/Nintendo)", emoji: "🎮",
                    category: .subscriptions, priority: .low, tMinusDays: 7,
                    brandColorHex: "#107C10", requires: [.usesGamingSubs]),
        
        // MARK: TV & Internet Providers
        CatalogItem(id: "xfinity", title: "Xfinity Account Address", emoji: "📺",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://customer.xfinity.com/move"),
                    brandColorHex: "#662DF8", requires: [.usesXfinity]),
        CatalogItem(id: "spectrum", title: "Spectrum Account Address", emoji: "📺",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.spectrum.net/support/manage-account/moving-services"),
                    brandColorHex: "#00549A", requires: [.usesSpectrum]),
        CatalogItem(id: "directv", title: "DirecTV Account Address", emoji: "📡",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.directv.com/move"),
                    brandColorHex: "#00A8E0", requires: [.usesDirecTV]),
        CatalogItem(id: "dish", title: "Dish Network Account Address", emoji: "📡",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://my.dish.com/move"),
                    brandColorHex: "#E21836", requires: [.usesDish]),
        CatalogItem(id: "verizon_fios", title: "Verizon Fios Account Address", emoji: "📺",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.verizon.com/home/moving/"),
                    brandColorHex: "#CD040B", requires: [.usesVerizonFios]),
        CatalogItem(id: "att", title: "AT&T Internet/TV Address", emoji: "🌐",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.att.com/moving/"),
                    brandColorHex: "#009FDB", requires: [.usesATT]),
        CatalogItem(id: "cox", title: "Cox Communications Address", emoji: "📺",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.cox.com/residential/move.html"),
                    brandColorHex: "#004B87", requires: [.usesCox]),
        CatalogItem(id: "optimum", title: "Optimum Account Address", emoji: "📺",
                    category: .subscriptions, priority: .high, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.optimum.net/moving/"),
                    brandColorHex: "#00B2E2", requires: [.usesOptimum]),
    ]

    // MARK: - 💪 FITNESS
    static let fitness: [CatalogItem] = [
        CatalogItem(id: "planetfitness", title: "Planet Fitness Membership", emoji: "💪",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.planetfitness.com"),
                    brandColorHex: "#8B1DBA", requires: [.usesPlanetFitness]),
        CatalogItem(id: "equinox", title: "Equinox Membership Address", emoji: "🏋️",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.equinox.com"),
                    brandColorHex: "#2C3E50", requires: [.usesEquinox]),
        CatalogItem(id: "lafitness", title: "LA Fitness Membership", emoji: "🏋️",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.lafitness.com"),
                    brandColorHex: "#003366", requires: [.usesLAFitness]),
        CatalogItem(id: "peloton", title: "Peloton Account Address", emoji: "🚴",
                    category: .subscriptions, priority: .medium, tMinusDays: -14,
                    deepLinkURL: URL(string: "https://www.onepeloton.com/profile"),
                    brandColorHex: "#CC0000", requires: [.usesPeloton]),
        CatalogItem(id: "classpass", title: "ClassPass Address", emoji: "🧘",
                    category: .subscriptions, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://classpass.com/account"),
                    brandColorHex: "#FF5A5F", requires: [.usesClassPass]),
        CatalogItem(id: "crossfit", title: "CrossFit Gym Membership", emoji: "🏋️",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#000000", requires: [.usesCrossFit]),
        CatalogItem(id: "orangetheory", title: "Orangetheory Membership", emoji: "🔥",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.orangetheory.com"),
                    brandColorHex: "#EF6C00", requires: [.usesOrangeTheory]),
        CatalogItem(id: "ymca", title: "YMCA Membership Address", emoji: "🏊",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.ymca.org"),
                    brandColorHex: "#003087", requires: [.usesYMCA]),
        CatalogItem(id: "24hourfitness", title: "24 Hour Fitness Membership", emoji: "💪",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#D32F2F", requires: [.uses24HourFitness]),
        CatalogItem(id: "lifetime", title: "Life Time Fitness Membership", emoji: "🏊",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#000000", requires: [.usesLifeTime]),
        CatalogItem(id: "jcc", title: "JCC Membership", emoji: "🏃",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#0055A4", requires: [.usesJCC]),
        CatalogItem(id: "vasa", title: "VASA Fitness Membership", emoji: "🏋️",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#C41230", requires: [.usesVASA]),
        CatalogItem(id: "eos", title: "EoS Fitness Membership", emoji: "🏋️",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#009BDF", requires: [.usesEoS]),
        CatalogItem(id: "chuze", title: "Chuze Fitness Membership", emoji: "🧘",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#F2A900", requires: [.usesChuze]),
        CatalogItem(id: "crunch", title: "Crunch Fitness Membership", emoji: "💪",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#0055A4", requires: [.usesCrunch]),
        CatalogItem(id: "anytimefitness", title: "Anytime Fitness Membership", emoji: "🏃",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#4C1C6C", requires: [.usesAnytimeFitness]),
    ]

    // MARK: - 🏬 MEMBERSHIPS
    static let memberships: [CatalogItem] = [
        CatalogItem(id: "aarp", title: "AARP Membership Address", emoji: "🌟",
                    category: .subscriptions, priority: .medium, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.aarp.org/account"),
                    brandColorHex: "#D40E14", requiresAny: [.isRetired, .hasMedicare]),
    ]

    // MARK: - 🐾 PETS
    static let pets: [CatalogItem] = [
        CatalogItem(id: "vet", title: "Veterinarian Records Transfer", emoji: "🐾",
                    category: .healthcare, priority: .high, tMinusDays: -7,
                    brandColorHex: "#27AE60", requires: [.hasPets]),
        CatalogItem(id: "pet_insurance", title: "Pet Insurance Address", emoji: "🐾",
                    category: .insurance, priority: .high, tMinusDays: -7,
                    brandColorHex: "#2E86C1", requires: [.hasPetInsurance]),
        CatalogItem(id: "microchip", title: "Pet Microchip Registry (HomeAgain / AKC)", emoji: "🔖",
                    category: .other, priority: .critical, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.homeagain.com"),
                    brandColorHex: "#8E44AD", requires: [.hasPets]),
        CatalogItem(id: "chewy", title: "Chewy Delivery Address", emoji: "🦴",
                    category: .subscriptions, priority: .medium, tMinusDays: 1,
                    deepLinkURL: URL(string: "https://www.chewy.com/account"),
                    brandColorHex: "#0099CC", requires: [.hasPets]),
        CatalogItem(id: "pet_autoship", title: "Auto-Ship Pet Food / Subscriptions", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: 1,
                    brandColorHex: "#D35400", requires: [.usesAutoShipPetFood]),
        CatalogItem(id: "rover", title: "Rover / Wag Address & Home Info", emoji: "🐕",
                    category: .other, priority: .medium, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.rover.com"),
                    brandColorHex: "#34A853", requires: [.hasPets]),
    ]

    // MARK: - 🏥 HEALTHCARE
    static let healthcare: [CatalogItem] = [
        CatalogItem(id: "primary_care", title: "Primary Care Doctor", emoji: "🩺",
                    category: .healthcare, priority: .high, tMinusDays: 7,
                    brandColorHex: "#C0392B", alwaysInclude: true),
        CatalogItem(id: "dentist", title: "Dentist", emoji: "🦷",
                    category: .healthcare, priority: .medium, tMinusDays: 14,
                    brandColorHex: "#2E86C1", alwaysInclude: true),
        CatalogItem(id: "eye_doctor", title: "Eye Doctor / Optometrist", emoji: "👁️",
                    category: .healthcare, priority: .medium, tMinusDays: 14,
                    brandColorHex: "#8E44AD", alwaysInclude: true),
        CatalogItem(id: "pharmacy", title: "Pharmacy (CVS / Walgreens / etc.)", emoji: "💊",
                    category: .healthcare, priority: .high, tMinusDays: 0,
                    deepLinkURL: URL(string: "https://www.cvs.com"),
                    brandColorHex: "#CC0000", alwaysInclude: true),
        CatalogItem(id: "mail_pharmacy", title: "Mail-Order Pharmacy (Express Scripts, OptumRx)", emoji: "📦",
                    category: .healthcare, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#16A085", requires: [.usesMailOrderPharmacy]),
        CatalogItem(id: "pediatrician", title: "Pediatrician & Children's Records", emoji: "👶",
                    category: .healthcare, priority: .critical, tMinusDays: -7,
                    brandColorHex: "#E91E63", requires: [.hasChildren]),
        CatalogItem(id: "health_insurance", title: "Health Insurance (update address)", emoji: "🛡️",
                    category: .insurance, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#1A5276", alwaysInclude: true),
        CatalogItem(id: "fsa_hsa", title: "Dependent Care FSA & Subsidies", emoji: "🏦",
                    category: .financial, priority: .high, tMinusDays: 14,
                    brandColorHex: "#8E44AD", requires: [.hasFSA]),
        CatalogItem(id: "life_insurance", title: "Life Insurance Billing Address", emoji: "📋",
                    category: .insurance, priority: .high, tMinusDays: -7,
                    brandColorHex: "#212F3D", requires: [.hasLifeInsurance]),
        CatalogItem(id: "renters_insurance", title: "Renter's Insurance (Pre-Move Activation)", emoji: "🏠",
                    category: .insurance, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#117ACA", requires: [.isRenting]),
        CatalogItem(id: "home_insurance", title: "Homeowner's Insurance", emoji: "🏡",
                    category: .insurance, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#C0392B", requires: [.isOwning]),
        CatalogItem(id: "auto_insurance", title: "Auto Insurance (new address = new rate)", emoji: "🚗",
                    category: .insurance, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#E74C3C", requiresAny: [.hasCar, .hasElectricVehicle]),
        CatalogItem(id: "umbrella_insurance", title: "Umbrella Insurance Policy", emoji: "☂️",
                    category: .insurance, priority: .medium, tMinusDays: -7,
                    brandColorHex: "#5D6D7E", requires: [.hasUmbrellaInsurance]),
    ]

    // MARK: - 💼 EMPLOYER & BUSINESS
    static let employer: [CatalogItem] = [
        CatalogItem(id: "employer_hr", title: "Employer HR & Payroll Address", emoji: "💼",
                    category: .employer, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#2C3E50", alwaysInclude: true),
        CatalogItem(id: "household_payroll", title: "Household Payroll & State Tax Board", emoji: "🧹",
                    category: .employer, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#9B59B6", requires: [.hasHouseholdHelp]),
        CatalogItem(id: "linkedin", title: "LinkedIn Profile Location", emoji: "🔗",
                    category: .employer, priority: .low, tMinusDays: 7,
                    deepLinkURL: URL(string: "https://www.linkedin.com/in/"),
                    brandColorHex: "#0077B5", alwaysInclude: true),
        CatalogItem(id: "business_banking", title: "Business Bank Account Address", emoji: "🏦",
                    category: .financial, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#117ACA", requires: [.runsBusiness]),
        CatalogItem(id: "business_insurance", title: "Business Insurance Address", emoji: "🛡️",
                    category: .insurance, priority: .high, tMinusDays: -14,
                    brandColorHex: "#27AE60", requires: [.runsBusiness]),
        CatalogItem(id: "cloud_infra", title: "Cloud Infrastructure Billing (AWS/GCP/Vercel)", emoji: "☁️",
                    category: .subscriptions, priority: .critical, tMinusDays: -7,
                    brandColorHex: "#F39C12", requires: [.usesCloudInfrastructure]),
    ]

    // MARK: - 📚 EDUCATION
    static let education: [CatalogItem] = [
        CatalogItem(id: "school_enrollment", title: "Children's School Enrollment", emoji: "🎒",
                    category: .education, priority: .critical, tMinusDays: -30,
                    brandColorHex: "#E74C3C", requires: [.hasChildren]),
        CatalogItem(id: "school_records", title: "School Records Transfer", emoji: "📚",
                    category: .education, priority: .critical, tMinusDays: -21,
                    brandColorHex: "#D35400", requires: [.hasChildren]),
        CatalogItem(id: "529_plan", title: "529 College Savings & Custodial Accounts", emoji: "📈",
                    category: .financial, priority: .high, tMinusDays: 14,
                    brandColorHex: "#2E86C1", requires: [.has529]),
        CatalogItem(id: "alumni", title: "College / Alumni Association Address", emoji: "🎓",
                    category: .education, priority: .low, tMinusDays: 14,
                    brandColorHex: "#7D3C98", alwaysInclude: true),
    ]

    // MARK: - 📝 LEGAL
    static let legal: [CatalogItem] = [
        CatalogItem(id: "will_trust", title: "Will & Estate Planning Documents", emoji: "📜",
                    category: .legal, priority: .high, tMinusDays: 14,
                    brandColorHex: "#2C3E50", requires: [.hasWill]),
        CatalogItem(id: "sec_of_state", title: "Secretary of State / Registered Agent", emoji: "🏛️",
                    category: .legal, priority: .critical, tMinusDays: -14,
                    brandColorHex: "#1B4F72", requires: [.runsBusiness]),
    ]
}
