import Foundation

extension ItemCatalog {
    /// Optional recall prompts. Brands require their explicit interview flag or an Add action;
    /// generic services require an Add action.
    /// Source checks and remaining coverage work are in CATALOG_REVIEW.md.
    static let recurringServices: [CatalogItem] = [
        CatalogItem(id: "stitch_fix", title: "Stitch Fix", emoji: "👗",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://support.stitchfix.com/support/solutions/articles/153000250486-how-to-update-your-shipping-address"),
                    requires: [.isAmerican, .usesStitchFix], reviewFamily: .shopping,
                    topic: .clothing, searchTerms: ["stitchfix", "styling box", "Fix"],
                    movingTip: "Update Account info and review the next Fix. On a family account, one shipping-address change applies to all profiles. Contact support if a label is already printed or a package has shipped."),
        CatalogItem(id: "firstleaf", title: "Firstleaf wine club", emoji: "🍷",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://help.firstleaf.com/hc/en-us"),
                    requires: [.isAmerican, .usesFirstleaf], reviewFamily: .shopping,
                    topic: .wine, searchTerms: ["first leaf", "wine membership"]),
        CatalogItem(id: "shipt", title: "Shipt grocery delivery", emoji: "🛒",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://help.shipt.com/how-do-i-change-my-address"),
                    requires: [.isAmerican, .usesShipt], reviewFamily: .shopping,
                    topic: .groceries),
        CatalogItem(id: "thrive_market", title: "Thrive Market membership & recurring orders", emoji: "🥑",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://help.thrivemarket.com/hc/en-us/articles/360056187972-Can-I-have-Recurring-orders-sent-to-a-different-address"),
                    requires: [.isAmerican, .usesThriveMarket], reviewFamily: .shopping,
                    topic: .groceries, searchTerms: ["autoship", "thrive"],
                    movingTip: "Recurring orders use your default shipping address. Review that address and your next shipment before the move; check an order already in progress separately."),
        CatalogItem(id: "misfits_market", title: "Misfits Market grocery deliveries", emoji: "🥕",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.misfitsmarket.com/"),
                    requires: [.isAmerican, .usesMisfitsMarket], reviewFamily: .shopping,
                    topic: .groceries),
        CatalogItem(id: "butcherbox", title: "ButcherBox deliveries", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.butcherbox.com/"),
                    requires: [.isAmerican, .usesButcherBox], reviewFamily: .shopping,
                    topic: .meals, searchTerms: ["butcher box", "meat", "seafood", "frozen"]),
        CatalogItem(id: "nuuly", title: "Nuuly clothing rental", emoji: "👚",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.nuuly.com/rent/help/shipping"),
                    requires: [.isAmerican, .usesNuuly], reviewFamily: .shopping,
                    topic: .clothing, searchTerms: ["rent clothes", "wardrobe"]),
        CatalogItem(id: "rent_the_runway", title: "Rent the Runway", emoji: "👗",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    deepLinkURL: URL(string: "https://www.renttherunway.com/"),
                    requires: [.isAmerican, .usesRentTheRunway], reviewFamily: .shopping,
                    topic: .clothing, searchTerms: ["RTR", "dress rental", "clothing rental"]),

        // Local providers and other brands remain useful without an exhaustive brand directory.
        CatalogItem(id: "local_grocery_delivery", title: "Local grocery delivery & store pickup accounts", emoji: "🛒",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .groceries),
        CatalogItem(id: "grocery_membership", title: "Grocery delivery passes & loyalty memberships", emoji: "🛒",
                    category: .subscriptions, priority: .medium, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .groceries,
                    searchTerms: ["grocery subscription", "delivery membership", "store rewards"]),
        CatalogItem(id: "csa_farm_share", title: "CSA farm share & produce box", emoji: "🥬",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .groceries,
                    searchTerms: ["community supported agriculture", "vegetable box", "farmers market"]),
        CatalogItem(id: "dairy_egg_delivery", title: "Milk, dairy & egg deliveries", emoji: "🥛",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .groceries),
        CatalogItem(id: "prepared_meal_delivery", title: "Prepared meals & local meal-prep service", emoji: "🥘",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .meals),
        CatalogItem(id: "specialty_food_subscription", title: "Meat, seafood & specialty-food subscriptions", emoji: "📦",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .meals),
        CatalogItem(id: "beverage_club", title: "Beer, spirits & other beverage clubs", emoji: "🍾",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .wine,
                    searchTerms: ["brewery", "distillery", "bottle club"]),
        CatalogItem(id: "tea_subscription", title: "Tea subscription & refill deliveries", emoji: "🫖",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .coffee),
        CatalogItem(id: "clothing_rental", title: "Other clothing & accessory rentals", emoji: "👚",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .clothing),
        CatalogItem(id: "grooming_refills", title: "Razors, shaving & grooming refills", emoji: "🪒",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .beauty),
        CatalogItem(id: "skincare_refills", title: "Skincare, cosmetics & hair-product subscriptions", emoji: "🧴",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .beauty),
        CatalogItem(id: "household_refills", title: "Cleaning, paper & household refill deliveries", emoji: "🧻",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .refills),
        CatalogItem(id: "filter_subscription", title: "Air & water filter subscriptions", emoji: "💧",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .home, requiresConfirmation: true, topic: .refills,
                    movingTip: "Update shipping details and check whether the filter size or model fits the new home before the next shipment."),
        CatalogItem(id: "water_delivery", title: "Bottled water delivery & dispenser rental", emoji: "💧",
                    category: .utilities, priority: .high, tMinusDays: -7,
                    reviewFamily: .home, discoveryContext: .housing, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .homeServices),
        CatalogItem(id: "vitamin_deliveries", title: "Vitamin & supplement subscriptions", emoji: "📦",
                    category: .healthcare, priority: .high, tMinusDays: -7,
                    reviewFamily: .healthPets, requiresConfirmation: true, topic: .refills),
        CatalogItem(id: "contact_lens_delivery", title: "Contact-lens refill deliveries", emoji: "👓",
                    category: .healthcare, priority: .high, tMinusDays: -7,
                    reviewFamily: .healthPets, requiresConfirmation: true, topic: .care),
        CatalogItem(id: "diaper_subscription", title: "Diaper, wipes & baby-supply subscriptions", emoji: "🍼",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .family, discoveryContext: .children, requiresConfirmation: true, topic: .refills),
        CatalogItem(id: "baby_food_subscription", title: "Baby & toddler food deliveries", emoji: "🥣",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .family, discoveryContext: .children, requiresConfirmation: true, topic: .meals),
        CatalogItem(id: "flower_subscription", title: "Flower & plant subscriptions", emoji: "💐",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .boxes),
        CatalogItem(id: "craft_hobby_box", title: "Craft, hobby & collectible boxes", emoji: "🎨",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .boxes),
        CatalogItem(id: "gift_subscriptions", title: "Gift subscriptions sent to you or someone else", emoji: "🎁",
                    category: .subscriptions, priority: .high, tMinusDays: -7,
                    reviewFamily: .shopping, requiresConfirmation: true, topic: .boxes,
                    movingTip: "Ask the person who manages a gift subscription to update its recipient address. Check gifts you send too, so changing your own address does not redirect them."),
        CatalogItem(id: "library_membership", title: "Local library card & borrowed items", emoji: "📚",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .reading),
        CatalogItem(id: "museum_zoo_membership", title: "Museum, zoo, aquarium & garden memberships", emoji: "🎟️",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .community),
        CatalogItem(id: "theater_cinema_membership", title: "Theater, cinema & season-ticket accounts", emoji: "🎭",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .community),
        CatalogItem(id: "recreation_center_pass", title: "Recreation center, pool & local sports passes", emoji: "🏊",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .community),
        CatalogItem(id: "adult_classes", title: "Adult classes, studios & hobby groups", emoji: "🎨",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .community),
        CatalogItem(id: "salon_membership", title: "Salon, barber & beauty-service memberships", emoji: "✂️",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .personalCare),
        CatalogItem(id: "massage_spa_membership", title: "Massage, spa & facial packages", emoji: "🧖",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .memberships, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .personalCare),
        CatalogItem(id: "self_storage", title: "Self-storage units & storage subscriptions", emoji: "📦",
                    category: .utilities, priority: .high, tMinusDays: -14,
                    reviewFamily: .home, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .storage),
        CatalogItem(id: "equipment_rental", title: "Tool libraries & rented household equipment", emoji: "🛠️",
                    category: .other, priority: .medium, tMinusDays: -7,
                    reviewFamily: .home, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .storage),
        CatalogItem(id: "laundry_pickup", title: "Laundry & dry-cleaning pickup service", emoji: "🧺",
                    category: .utilities, priority: .high, tMinusDays: -7,
                    reviewFamily: .home, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .homeServices),
        CatalogItem(id: "hvac_maintenance", title: "HVAC & appliance maintenance plans", emoji: "🛠️",
                    category: .utilities, priority: .medium, tMinusDays: -7,
                    reviewFamily: .home, discoveryContext: .housing, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .homeServices),
        CatalogItem(id: "pet_grooming", title: "Pet grooming & recurring appointments", emoji: "🐾",
                    category: .healthcare, priority: .medium, tMinusDays: -7,
                    reviewFamily: .healthPets, discoveryContext: .pets, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .pets),
        CatalogItem(id: "pet_daycare_training", title: "Pet daycare, boarding & training plans", emoji: "🐕",
                    category: .healthcare, priority: .medium, tMinusDays: -7,
                    reviewFamily: .healthPets, discoveryContext: .pets, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .pets),
        CatalogItem(id: "home_care_service", title: "Home care, caregiver & support visits", emoji: "🏡",
                    category: .healthcare, priority: .high, tMinusDays: -14,
                    reviewFamily: .healthPets, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .care),
        CatalogItem(id: "medical_supply_delivery", title: "Medical supplies & equipment deliveries", emoji: "📦",
                    category: .healthcare, priority: .high, tMinusDays: -14,
                    reviewFamily: .healthPets, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .care),
        CatalogItem(id: "meal_support_service", title: "Community meal deliveries & support programs", emoji: "🥘",
                    category: .healthcare, priority: .high, tMinusDays: -14,
                    reviewFamily: .healthPets, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .care),
        CatalogItem(id: "package_locker", title: "Building package lockers & delivery instructions", emoji: "📦",
                    category: .utilities, priority: .high, tMinusDays: -3,
                    reviewFamily: .home, requiresConfirmation: true, topic: .deliveryAccess),
        CatalogItem(id: "private_mailbox", title: "PO box, private mailbox & virtual-mail services", emoji: "📬",
                    category: .postal, priority: .high, tMinusDays: -14,
                    reviewFamily: .identity, requiresConfirmation: true, moveAction: .reviewTransfer, topic: .deliveryAccess),
        CatalogItem(id: "coworking_membership", title: "Coworking space & business-mail memberships", emoji: "💼",
                    category: .employer, priority: .medium, tMinusDays: -14,
                    reviewFamily: .work, discoveryContext: .work, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .storage),
        CatalogItem(id: "professional_association", title: "Professional associations & union memberships", emoji: "💼",
                    category: .employer, priority: .medium, tMinusDays: -7,
                    reviewFamily: .work, requiresConfirmation: true, topic: .community),
        CatalogItem(id: "car_wash_membership", title: "Car wash & detailing memberships", emoji: "🚗",
                    category: .travel, priority: .medium, tMinusDays: -7,
                    reviewFamily: .travel, discoveryContext: .vehicle, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .vehicleCare),
        CatalogItem(id: "ev_charging_accounts", title: "EV charging accounts & subscriptions", emoji: "🔌",
                    category: .travel, priority: .medium, tMinusDays: -7,
                    reviewFamily: .travel, discoveryContext: .vehicle, requiresConfirmation: true, topic: .vehicleCare),
        CatalogItem(id: "monthly_parking", title: "Monthly parking & garage subscriptions", emoji: "🅿️",
                    category: .travel, priority: .high, tMinusDays: -14,
                    reviewFamily: .travel, discoveryContext: .vehicle, requiresConfirmation: true,
                    moveAction: .reviewTransfer, topic: .vehicleCare)
    ]
}
